name: match_card_game
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  flip_card: ^0.6.0
  flutter:
    sdk: flutter
  lottie: ^2.1.0
  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/.
    - assets/brain_animation.json
  #   - images/a_dot_ham.jpeg